### ISSUE TITLE
Design: Display Errors When Sending Zec

### ISSUE THREAD

**Issue by ccjernigan** [Electric-Coin-Company/zashi-android#340]
The send ZEC screen should provide good feedback to the user about errors on the form input.  Some examples of errors:

- [x] Amount too small (cannot cover fee)
- [x] Amount too large (exceeds current balance)
- [x] Invalid amount
- [x] Bad address
- [x] Insufficient funds
- [x] Invalid address

**Comment by str4d** [comment]
@HonzaR says the current status of the Zashi UI is that:
- Some validation is performed while the user is interacting with the send form fields, but no error messages are displayed; instead the Send button is disabled. Users have no feedback about what the problem is in this case.
- All other validation occurs when the Send button is clicked, and any resulting error is then displayed in the screen. This does convey error information to users, but only after they think they have finished preparing for the send, instead of in real time.
